name: build-and-deploy-book

# Trigger the workflow on push to main branch and PRs
on: [push, pull_request]

# This job installs dependencies, builds the book, and deploys the html
jobs:
  build-and-deploy-book:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        # Can be "open", "closed", or "all".  Defaults to "open".
        state: open
    # This will echo "Your PR is 7", or be skipped if there is no current PR.
    - name: Get PR number
      run: echo "Your PR is ${PR}"
      if: success() && steps.findPr.outputs.number
      env:
        PR: ${{ steps.findPr.outputs.pr }}
    - name: 📦 Cache Conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment.yaml') }}
    - uses: conda-incubator/setup-miniconda@v2
      name: 🐍 Set up Conda environment
      with:
        environment-file: environment.yaml
        activate-environment: L96M2lines # Defined in environment.yaml
        channels: conda-forge
        mamba-version: '*'
        channel-priority: strict
        auto-update-conda: false
        python-version: ${{ matrix.python-version }}
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - name: 👀 Check Conda environment
      shell: bash -l {0}
      run: |
          conda info
          conda list
    - name: 📦 Cache Notebooks
      uses: actions/cache@v2
      with:
        path: _notebook_cache
        key: notebook_cache-${{hashFiles('notebooks/*.ipynb', 'notebooks/*.py') }}
        restore-keys: |
            notebook_cache-${{hashFiles('notebooks/*.ipynb', 'notebooks/*.py') }}
            notebook_cache-
    - name: 📖 Build the book
      shell: bash -l {0}
      run:  |
        mkdir -p _notebook_cache
        jupyter-book build .
    - name: 🚀 Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
    - name: 🚀 Deploy Preview to GitHub Pages
      if: ${{ steps.findPr.outputs.pr }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
        destination_dir: preview-${{ steps.findPr.outputs.pr }}
    - name: Post comment on PR
      uses: actions/github-script@v5
      if: success() && steps.findPr.outputs.number
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚀 A preview of the book is available at https://m2lines.github.io/L96_demo/preview-${{ steps.findPr.outputs.pr }}'
          })
